import React from 'react';
import { LegalPageLayout } from './LegalPageLayout';

export const TermsOfService: React.FC = () => {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="May 2026">
      <section>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using the Velocity website and its associated tools at{' '}
          <a href="https://lsesuvelocity.com">lsesuvelocity.com</a> (the "Service"), you agree to be bound by
          these Terms of Service ("Terms"). If you do not agree to these Terms, you must not use the Service.
        </p>
      </section>

      <section>
        <h2>2. About the Service</h2>
        <p>
          The Velocity website is operated by LSESU Velocity ("Velocity", "we", "us",
          "our"), a student society at the London School of Economics and Political Science Students' Union
          (LSESU). The Service includes the Velocity website and its associated tools, such as
          Launchpad, which allows users to submit startup ideas and receive AI-generated feedback
          through a browser-entered API key workflow. The current Launchpad adapter uses
          Google Gemini via Google AI Studio.
        </p>
      </section>

      <section>
        <h2>3. Eligibility</h2>
        <p>
          The Service is built and maintained by LSESU Velocity, a student society at LSE, but is publicly
          available to anyone aged 18 or over. Launchpad requires you to supply your own supported
          provider API key; no LSE affiliation is needed to use it. By using the Service, you represent that
          you are at least 18 years old.
        </p>
      </section>

      <section>
        <h2>4. Acceptable Use</h2>
        <p>When using the Service, you agree not to:</p>
        <ul>
          <li>Submit content that is unlawful, abusive, threatening, defamatory, or otherwise objectionable.</li>
          <li>Attempt to manipulate the AI system through prompt injection, jailbreaking, or similar techniques.</li>
          <li>Use the Service to generate content that infringes on the intellectual property rights of others.</li>
          <li>Use an API key that you are not authorised to use or that violates the selected provider&rsquo;s terms.</li>
          <li>Ignore provider billing, rate-limit, data handling, age, or regional requirements that apply to your use.</li>
          <li>Share your API key or allow unauthorised third parties to access the Service through your session.</li>
          <li>Attempt to reverse-engineer, decompile, or extract the source code or underlying algorithms of the Service.</li>
          <li>Use automated scripts, bots, or other tools to access the Service in a manner that exceeds reasonable usage.</li>
          <li>Interfere with or disrupt the integrity or performance of the Service.</li>
        </ul>
        <p>
          We reserve the right to suspend or terminate access for any user who violates these terms.
        </p>
      </section>

      <section>
        <h2>5. AI-Generated Content Disclaimer</h2>
        <p>
          Feedback and content generated by our tools is produced by artificial intelligence from the selected
          provider and is intended for informational and educational purposes only. It does not constitute
          professional business, legal, or financial advice.
        </p>
        <p>
          We make no guarantees regarding the accuracy, completeness, reliability, or suitability of
          AI-generated content. AI models may produce incorrect, misleading, or biased outputs.
          You should independently verify any information or advice before relying on it.
        </p>
        <p>
          Velocity, LSESU, and LSE are not responsible for any decisions made based on AI-generated feedback.
        </p>
      </section>

      <section>
        <h2>6. Intellectual Property & Confidentiality</h2>
        <p>
          <strong>Your ideas belong to you.</strong> Submitting content to our tools does
          not transfer any intellectual property rights to Velocity, LSESU, or any third party.
        </p>
        <p>
          We take the confidentiality of your submissions seriously. Launchpad stores analysis results
          in your browser only and does not persist them on our servers. However, please be aware that:
        </p>
        <ul>
          <li>
            Content you submit is sent to the selected AI provider for processing using your own API key.
            Your submissions are processed by that provider in accordance with its terms of service,
            privacy policy, billing rules, and regional restrictions.
          </li>
          <li>
            We cannot guarantee absolute confidentiality once data is transmitted to third-party services.
          </li>
          <li>
            If your submission is highly sensitive or commercially valuable, you should consider whether
            submitting it to an AI-powered tool is appropriate for your needs.
          </li>
        </ul>
        <p>
          The Velocity website, its design, branding, and original content (excluding user submissions and
          AI-generated output) are the intellectual property of LSESU Velocity.
        </p>
      </section>

      <section>
        <h2>7. Service Availability</h2>
        <p>
          The Velocity website and tools are a student society project provided on a best-effort basis. We do not
          guarantee that the Service will be available at all times or without interruption. We may modify,
          suspend, or discontinue the Service (or any part of it) at any time without prior notice.
        </p>
        <p>
          We are not liable for any loss or inconvenience caused by downtime, service interruptions,
          or discontinuation of the Service.
        </p>
      </section>

      <section>
        <h2>8. Limitation of Liability</h2>
        <p>
          The Service is provided "as is" and "as available" without warranties of any kind, whether
          express or implied, including but not limited to implied warranties of merchantability, fitness
          for a particular purpose, and non-infringement.
        </p>
        <p>
          To the fullest extent permitted by law, Velocity, LSESU, LSE, and their respective members,
          officers, and volunteers shall not be liable for any indirect, incidental, special, consequential,
          or punitive damages, or any loss of profits, data, or goodwill arising out of or in connection
          with your use of the Service.
        </p>
        <p>
          This is a student society project built and maintained by volunteers. The Service is not a
          commercial product and should not be relied upon as such.
        </p>
      </section>

      <section>
        <h2>9. Termination</h2>
        <p>
          We may terminate or suspend your access to the Service at any time, with or without cause, and
          with or without notice. Upon termination, your right to use the Service ceases immediately.
        </p>
        <p>
          You may stop using the Service at any time. If you wish to have your data deleted, please
          contact us at <a href="mailto:velocity@lsesu.org">velocity@lsesu.org</a>.
        </p>
      </section>

      <section>
        <h2>10. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of England and Wales.
          Any disputes arising under or in connection with these Terms shall be subject to the exclusive
          jurisdiction of the courts of England and Wales.
        </p>
      </section>

      <section>
        <h2>11. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Any changes will be posted on this page with an
          updated "Last updated" date. Continued use of the Service after changes are posted constitutes
          acceptance of the revised Terms.
        </p>
      </section>

      <section>
        <h2>12. Contact</h2>
        <p>
          If you have any questions about these Terms, please contact us at:
        </p>
        <p>
          <a href="mailto:velocity@lsesu.org">velocity@lsesu.org</a>
        </p>
      </section>
    </LegalPageLayout>
  );
};
